### ISSUE TITLE
Missing source map

### ISSUE THREAD

**Issue by thefrana** [epicweb-dev/invariant#9]
Hi,
I am getting this error when the invariant check is false. Do you happen to know what is causing that? I am using standard Remix app and some features of Epic Stack.

```
Error: ENOENT: no such file or directory, open '.../node_modules/@epic-web/invariant/dist/index.js.map'
    at Object.readFileSync (node:fs:453:20)
    at Array.retrieveSourceMap (.../node_modules/@remix-run/serve/dist/cli.js:50:37)
    at .../node_modules/source-map-support/source-map-support.js:85:24
    at mapSourcePosition (.../node_modules/source-map-support/source-map-support.js:216:21)
    at wrapCallSite (.../node_modules/source-map-support/source-map-support.js:397:20)
    at Function.prepareStackTrace (.../node_modules/source-map-support/source-map-support.js:446:39)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at getStackString (node:internal/util/inspect:1240:16)
    at formatError (node:internal/util/inspect:1369:15)
```

Thank you

EDIT: this happens when I use Node v20. If I switch to Node v18, I get the same error but for `@epic-web/remember`

EDIT 2: the problem is with Remix v2.4. After downgrade to v2.3 as in Epic Stack, it works flawlessly.

**Comment by kentcdodds** [comment]
Yep, that's a Remix issue. Could you open an issue on remix? They need to handle situations where the source map file doesn't exist.
